remote_theme: jekyll/minima
title: d3matt.com
description: Trying github.io
#paginate: 3


#header_pages:
# - about.md

author:
  name: Matthew Stoltenberg
  email: d3matt@gmail.com

minima:
  skin: dark
  social_links:
    github: d3matt
    facebook: d3matt
    linkedin: d3matt

show_excerpts: true
